MyMealMate/urls.py
from django.urls import path
from MyMealMate import views

app_name = 'MyMealMate'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('user_hub/', views.user_hub, name='user_hub'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit_profile/', views.edit_profile, name='edit_profile'),
    path('my_meals/', views.my_meals, name='my_meals'),
    path('my_meals/new_meal/', views.new_meal, name='new_meal'),
    path('my_meals/<slug:meal_name_slug>/', views.meal, name='meal'),
    path('my_meals/<slug:meal_name_slug>/edit_meal/', views.edit_meal, name='edit_meal'),
    path('my_meals/<slug:meal_name_slug>/add_meal_to_shopping_list/', views.add_meal_to_shopping_list, name='add_meal_to_shopping_list'),
    path('my_meals/<slug:meal_name_slug>/delete_meal/', views.delete_meal, name='delete_meal'),
    path('mymeals/<slug:meal_name_slug>/add_ingredient/', views.add_ingredient, name='add_ingredient'),
    path('mymeals/<slug:meal_name_slug>/delete_ingredient/', views.delete_ingredient, name='delete_ingredient'),
    path('mymeals/<slug:meal_name_slug>/edit_ingredient/', views.edit_ingredient, name='edit_ingredient'),
    path('user_hub/add_meal_of_the_day/', views.add_meal_of_the_day, name='add_meal_of_the_day'),
    path('schedule/', views.schedule, name='schedule'),
    path('delete_scheduled_meal/', views.delete_scheduled_meal, name='delete_scheduled_meal'),
    path('shopping_list/', views.shopping_list, name='shopping_list'),
    path('shopping_list/clear_all', views.clear_all, name='clear_all'),
    path('shopping_list/clear_completed/', views.clear_completed, name='clear_completed'),
    path('shopping_list/clicked/<int:item_id>/', views.clicked_item, name='clicked'),
    path('user_hub/clicked_from_hub/<int:item_id>/', views.clicked_item_from_hub, name='clicked_from_hub'),
    path('shopping_list/edit_shopping_list/', views.edit_shopping_list, name='edit_shopping_list'),
    path('shopping_list/edit_shopping_list/add_item', views.add_shopping_list_item, name='add_item'),
    path('shopping_list/edit_shopping_list/edit_item', views.edit_shopping_list_item, name='edit_item'),
    path('shopping_list/edit_shopping_list/delete_item', views.delete_shopping_list_item, name='delete_item'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/edit_profile/delete_account/', views.delete_account, name="delete_account"),
]

mymealmateapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from MyMealMate import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('MyMealMate/', include('MyMealMate.urls')),
    #======================================
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyMealMate/forms.py
from django import forms
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from MyMealMate.models import UserProfile
from MyMealMate.models import Meal, ShoppingListItem, Ingredient, Schedule, Day

class DeleteScheduledMealForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        super(DeleteScheduledMealForm, self).__init__(*args, **kwargs)
        scheduled_meals = Meal.objects.filter(day__schedule__user=user).order_by('day__date')
        self.fields['meal'].queryset = scheduled_meals

    meal = forms.ModelChoiceField(queryset=Meal.objects.none(), empty_label=None)
    # date = forms.DateField(widget=forms.SelectDateWidget)x

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email', 'password' ,)
        

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture', )

    def save(self, commit=True):
        userProfile = super().save(commit=False)
        if not self.cleaned_data.get('picture'):
            userProfile.picture = "default_profile.jpg"
        if commit:
            userProfile.save()
        return userProfile

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields =('username', 'first_name', 'email',)

class EditPictureForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)

class MealEditForm(forms.ModelForm):
    class Meta:
        model = Meal
        fields = ('name', 'image', 'url', 'instructions', )

class MealForm(forms.ModelForm):
    class Meta:
        model = Meal
        fields = ('name', 'image', 'url', )

    def __init__(self, *args, **kwargs):
        super(MealForm, self).__init__(*args, **kwargs)
        self.fields['name'].unique = False
        self.fields['name'].label = 'Name (required):'
        self.fields['url'].label = 'Recipe URL:'

    def save(self, commit=True):
        meal = super().save(commit=False)
        if not self.cleaned_data.get('image'):
            meal.image = "default_meal_image.jpg"
        if commit:
            meal.save()
        return meal

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ('name', 'amount', 'unit',)

class ShoppingListForm(forms.ModelForm):
    name = forms.CharField(max_length=30, help_text="Name:")
    amount = forms.IntegerField(help_text="Amount:", required=False, min_value=0)
    unit = forms.CharField(max_length=30, help_text="Unit:", required=False)
    checked = forms.BooleanField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = ShoppingListItem
        fields = ('name', "amount", "unit", "checked",)

MyMealMate/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.forms import formset_factory
from django.views.decorators.csrf import csrf_exempt
from django.template.defaultfilters import slugify
from MyMealMate.forms import *
from MyMealMate.models import *
from MyMealMate.forms import MealForm, MealEditForm
from datetime import datetime,timedelta
from http import client
from http import cookiejar
import json
import http
from fractions import Fraction
import re
from django.core.files.base import ContentFile
import os
import urllib.request

def home(request):
    context_dict = {'nbar': 'home'}
    set_meal_cookie(request)
    context_dict['meal_of_the_day'] = request.session['meal_of_the_day']

    if request.user.is_authenticated:
        return redirect(reverse('MyMealMate:user_hub'))

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:

            if user.is_active:
                login(request, user)
                return redirect(reverse('MyMealMate:user_hub'))
            
            else:
                context_dict['error_message'] = "Your MyMealMate account is disabled."
                return render(request, 'MyMealMate/home.html', context=context_dict)

        else:
            print("Invalid login details.")
            context_dict['error_message'] = "Invalid login details supplied."
            return render(request, 'MyMealMate/home.html', context=context_dict)

    else:
        return render(request, 'MyMealMate/home.html', context=context_dict)


def signup(request):
    context_dict = {'nbar': 'signup'}

    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True
            login(request, user)

            return redirect(reverse('MyMealMate:user_hub'))
        else:
            print(user_form.errors, profile_form.errors)
    
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    set_meal_cookie(request)
    context_dict = {'user_form': user_form,
                    'profile_form':profile_form,
                    'registered': registered,
                    'meal_of_the_day': request.session['meal_of_the_day']}

    response = render(request, 'MyMealMate/signup.html', context = context_dict)
    return response


@login_required
def user_logout(request):
    meal_of_the_day = request.session.get('meal_of_the_day', None)
    last_set = request.session.get('last_set', None)
    logout(request)
    request.session['meal_of_the_day'] = meal_of_the_day
    request.session['last_set'] = last_set
    return redirect(reverse('MyMealMate:home'))


@login_required
def delete_account(request):
    user = request.user
    user.delete()
    return redirect(reverse('MyMealMate:home'))


@login_required
def user_hub(request):
    set_meal_cookie(request)
    meal_of_the_day = request.session['meal_of_the_day']
    shopping_list = ShoppingList.objects.get_or_create(user=request.user)[0]
    shopping_list_items = ShoppingListItem.objects.filter(shoppingList=shopping_list).order_by("checked")\
    
    # next 7 days 
    user_schedule = Schedule.objects.get_or_create(user=request.user)[0]

    upcoming_meals = []
    for i in range(7):
        day = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0) + timedelta(days=i)
        day_name = day.strftime("%A")
        meals = [meal.name for meal in Day.objects.get_or_create(schedule=user_schedule, date=day)[0].scheduledMeals.all()]
        if not meals:
            meals = ["No meals scheduled"]
        upcoming_meals.append((day_name, meals))

    context_dict = {'nbar': 'user_hub',
                    'user': request.user,
                    'meal_of_the_day': meal_of_the_day,
                    'has_meal_of_the_day': userHasMeal(request,meal_of_the_day['strMeal']),
                    'shopping_list_items': shopping_list_items,
                    'upcoming_meals': upcoming_meals}
    response = render(request, 'MyMealMate/user_hub.html', context = context_dict)
    return response

@login_required
def profile(request):
    user = request.user
    picture = UserProfile.objects.get(user=user).picture
    context_dict = {'nbar': 'profile', 
                    'user': user,
                    'profile_picture': picture}
    
    response = render(request, 'MyMealMate/profile.html', context = context_dict)
    return response


@login_required
def edit_profile(request):
    user = request.user
    userProfile = UserProfile.objects.get(user=user)
        
    if request.method == "POST":
        profile_form = EditProfileForm(request.POST, instance=user)
        picture_form = EditPictureForm(request.POST, instance=userProfile)

        if profile_form.is_valid() and picture_form.is_valid():

            if 'picture' in request.FILES:
                userProfile.picture = request.FILES['picture']
            else:
                userProfile.picture = "default_profile.jpg"

            profile_form.save()
            picture_form.save()
            return redirect(reverse('MyMealMate:profile'))
    
    else:
        profile_form = EditProfileForm(instance=user)
        picture_form = EditPictureForm(instance=userProfile)

    context_dict = {'nbar': 'profile',
                    'user': user,
                    'profile_picture': userProfile.picture,
                    'edit_profile_form': profile_form,
                    'edit_picture_form': picture_form,}
    
    response = render(request, 'MyMealMate/edit_profile.html', context = context_dict)
    return response


@login_required
def my_meals(request):
    context_dict = {'nbar': 'my_meals'}
  
    meals = Meal.objects.filter(user=request.user)
    recent_meals = Meal.objects.filter(user=request.user).order_by('-id')[:5]
    context_dict["meals"] = meals
    context_dict["username_slug"] = slugify(request.user.username)
    context_dict["recent_meals"] = recent_meals

    response = render(request, 'MyMealMate/my_meals.html', context=context_dict)
    return response


@login_required
def new_meal(request):

    if request.method == 'POST':
        form = MealForm(request.POST, request.FILES)
        if form.is_valid():
            meal = form.save(commit=False)
            meal.user = request.user  
            meal.save()
            return redirect(reverse('MyMealMate:edit_meal', kwargs={'meal_name_slug': meal.slug}))
    else:
        form = MealForm()

    return render(request, 'MyMealMate/new_meal.html', {'form': form})


@login_required
def meal(request, meal_name_slug):
    meal = Meal.objects.filter(user=request.user).get(slug=meal_name_slug)
    context_dict = {'nbar': 'meal', "meal": meal, "username_slug": slugify(request.user.username)}

    response = render(request, 'MyMealMate/meal.html', context = context_dict)
    return response


def edit_meal(request, meal_name_slug):
    meal = get_object_or_404(Meal, slug=meal_name_slug, user=request.user)

    if request.method == 'POST':
        form = MealEditForm(request.POST, request.FILES, instance=meal)
        if form.is_valid():
            meal = form.save(commit=False)
            # Save the meal and retrieve the updated ingredients list
            ingredients_list = request.POST.getlist('ingredients')
            meal.save()
            return render(request, 'MyMealMate/meal.html', {'meal': meal, 'ingredients_list': ingredients_list})
    else:
        form = MealEditForm(instance=meal)
    return render(request, 'MyMealMate/edit_meal.html', {'form': form, 'meal': meal})

@csrf_exempt
def add_ingredient(request, meal_name_slug):
    if request.method == 'POST':
        name = request.POST.get('name')
        amount = request.POST.get('amount')
        unit = request.POST.get('unit')
        meal = get_object_or_404(Meal, slug=meal_name_slug, user=request.user)

        # Create the new ingredient and associate it with the meal
        ingredient = Ingredient.objects.create(name=name, amount=amount, unit=unit)
        meal.ingredients.add(ingredient)

        return JsonResponse({'id': ingredient.id})

@csrf_exempt
def edit_ingredient(request, meal_name_slug):
    if request.method == 'GET':
        ingredient_id = request.GET.get('ingredient_id')
        try:
            ingredient = Ingredient.objects.get(id=ingredient_id)
            data = {
                'name': ingredient.name,
                'amount': ingredient.amount,
                'unit': ingredient.unit
            }
            response = JsonResponse(data)
            
            return response
        except Ingredient.DoesNotExist:
            return JsonResponse({'error': 'Ingredient not found'}, status=404)
    else:
        return JsonResponse({'error': 'Method not allowed'}, status=405)

@csrf_exempt
def delete_ingredient(request, meal_name_slug):
    if request.method == 'POST':
        # Retrieve the meal
        meal = get_object_or_404(Meal, slug=meal_name_slug, user=request.user)
        ingredient_id = request.POST.get('ingredient_id')
        # Retrieve the ingredient
        ingredient = get_object_or_404(Ingredient, id=ingredient_id)
        

templates/MyMealMate/base.html
<!DOCTYPE html>
{%load staticfiles%}
{%load MyMealMate_template_tags%}

<html>
  <head>
      <title>
        MyMealMate -
        {% block title_block %}
        {% endblock %}
      </title>
      <link rel="stylesheet" href="{% static 'css/styles.css' %}">
      {% block stylesheet_block %}
      {% endblock %}
      {% block script_block %}
      {% endblock %}
  </head>

  <body>
    <nav>
      <div class="logo">
          <a href="{% url 'MyMealMate:user_hub' %}"><img src="{% static 'images/small_logo.png' %}" alt="Meal Mate Logo"></a></a>
      </div>
  
      <ul class="nav-links">
          {% if user.is_authenticated %}
          <li><a href="{% url 'MyMealMate:user_hub' %}" class="{% if nbar == 'user_hub' %}active{% endif %}">User Hub</a></li>
          <li><a href="{% url 'MyMealMate:my_meals' %}" class="{% if nbar == 'my_meals' %}active{% endif %}">My Meals</a></li>
          <li><a href="{% url 'MyMealMate:schedule' %}" class="{% if nbar == 'schedule' %}active{% endif %}">Schedule</a></li>
          <li><a href="{% url 'MyMealMate:shopping_list' %}" class="{% if nbar == 'shopping_list' %}active{% endif %}">Shopping List</a></li>
          <li><a href="{% url 'MyMealMate:profile' %}" class="{% if nbar == 'profile' %}active{% endif %}">Profile</a></li>
          {% endif %}
      </ul>
  
      <div class="auth-links">
          {% if user.is_authenticated %}
            <a href="{% url 'MyMealMate:logout' %}">Logout</a>
          {% endif %}
      </div>
    </nav>

    <div class="main">
      <div class="main-content">
      {% block body_block %}
      {% endblock %}
      </div>
    </div>
  </body>
</html>

templates/MyMealMate/edit_meal.html
<!DOCTYPE html>
{% extends 'MyMealMate/base.html' %}
{% load staticfiles %}
{%load MyMealMate_template_tags%}


{% block stylesheet_block %}
    <link rel="stylesheet" href="{% static 'css/meal.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block title_block %}
    Edit Meal
{% endblock %}

{% block body_block %}
    <h1>{{ meal.name }} - Edit</h1>
    <div class="content">
      <div class="meal-list">
      <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="button" type="submit">Save changes</button>
          <button class="button" type="submit" formaction="{% url 'MyMealMate:delete_meal' meal.slug %}">Delete Recipe</button>
      </form>
      </div>
      <div class="sidebar" style="height: 485px; overflow-y: auto;">
      <h3>Ingredients</h3>
      <form name="ingredient" method="post" enctype="multipart/form-data">
          {% csrf_token %}
        <ul id="ingredient-list">
            {% for ingredient in meal.ingredients.all %}
              <li>{{ ingredient.name }} - {{ ingredient.amount|remove_decimal_if_integer }} {{ ingredient.unit }}
                <a href="#" class="edit-ingredient" data-ingredient-id="{{ ingredient.id }}"><i class="fa fa-pencil"></i></a>
                <a href="#" class="delete-ingredient" data-ingredient-id="{{ ingredient.id }}"><i class="fa fa-trash"></i></a>
              </li>
            {% endfor %}
        </ul>
      </form>
      
        <!-- Add new ingredient form -->
        <form method="post" enctype="multipart/form-data" id="add-ingredient-form">
          {% csrf_token %}
          <input type="text" id="new-ingredient-name" placeholder="Ingredient name" required>
          <input type="number" id="new-ingredient-amount" placeholder="Amount" required>
          <input type="text" id="new-ingredient-unit" placeholder="Unit" required>
          <button type="button" id="add-ingredient" class="button">Add Ingredient</button>
        </form>
        
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <script>
          // jQuery document ready function
          $(document).ready(function() {
            // Handle adding new ingredients without refreshing the page
            $("#add-ingredient").on("click", function() {
              var name = $("#new-ingredient-name").val();
              var amount = $("#new-ingredient-amount").val();
              var unit = $("#new-ingredient-unit").val();
      
              if (name && amount) {
                console.log("Adding ingredient...") 

                $.ajax({
                  type: "POST",
                  url: "{% url 'MyMealMate:add_ingredient' meal_name_slug=meal.slug %}",
                  data: {
                      'name': name,
                      'amount': amount,
                      'unit': unit,
                      'meal_id': '{{ meal.id }}',  // Pass the meal ID to associate the ingredient with the meal
                      'csrfmiddlewaretoken': '{{ csrf_token }}'
                  },
                  success: function(response) {
                      console.log("ingredient added successfully")
                      // Append new ingredient to the list on success
                      $("#ingredient-list").append('<li>' + name + ' - ' + amount + ' ' + unit +
                          ' <a href="#" class="edit-ingredient" data-ingredient-id="' + response.id + '"><i class="fa fa-pencil"></i></a>' +
                          ' <a href="#" class="delete-ingredient" data-ingredient-id="' + response.id + '"><i class="fa fa-trash"></i></a></li>');

                      // Clear input fields
                      $("#new-ingredient-name").val("");
                      $("#new-ingredient-amount").val("");
                      $("#new-ingredient-unit").val("");
                  },
                  error: function(error) {
                      console.log("Error adding ingredient")
                      console.log(error);
                  }
                });
              } 
            });

            $(".edit-ingredient").on("click", function() {
              var ingredientId = $(this).data("ingredient-id");
              var listItem = $(this).closest("li");
              // Send AJAX request to get ingredient details
              $.ajax({
                  type: "GET",
                  url: "{% url 'MyMealMate:edit_ingredient' meal.slug %}",
                  data: {
                      'ingredient_id': ingredientId,
                  },
                  success: function(response) {
                      // Populate the form fields with ingredient details
                      $("#new-ingredient-name").val(response.name);
                      $("#new-ingredient-amount").val(response.amount);
                      $("#new-ingredient-unit").val(response.unit);
                  },
                  error: function(xhr, textStatus, errorThrown) {
                      console.log("Error:", errorThrown);
                  }
              });
              $.ajax({
                  type: "POST",
                  url: "{% url 'MyMealMate:delete_ingredient' meal_name_slug=meal.slug %}",
                  data: {
                      'ingredient_id': ingredientId,
                      'csrfmiddlewaretoken': '{{ csrf_token }}'
                  },
                  success: function(response) {
                    console.log("Ingredient deleted successfully");
                    // Remove the ingredient from the list on success
                    listItem.remove();
                },
                  error: function(error) {
                    console.log("Error deleting ingredient");
                    console.log(error);
                  }
          });
        });
      
            $("#ingredient-list").on("click", ".delete-ingredient", function() {
              var ingredientId = $(this).data("ingredient-id");
              var listItem = $(this).closest("li");
              $.ajax({
                  type: "POST",
                  url: "{% url 'MyMealMate:delete_ingredient' meal_name_slug=meal.slug %}",
                  data: {
                      'ingredient_id': ingredientId,
                      'csrfmiddlewaretoken': '{{ csrf_token }}'
                  },
                  success: function(response) {
                    console.log("Ingredient deleted successfully");
                    // Remove the ingredient from the list on success
                    listItem.remove();
                },
                  error: function(error) {
                    console.log("Error deleting ingredient");
                    console.log(error);
                  }
              });
            });
          });
          
        </script>
        </div>
    </div>
{% endblock %}

templates/MyMealMate/index.html
<!DOCTYPE html>
{% extends 'MyMealMate/base.html' %}
{% load staticfiles %}

templates/MyMealMate/meal.html
<!DOCTYPE html>
{% extends 'MyMealMate/base.html' %}
{% load staticfiles %}
{%load MyMealMate_template_tags%}

{% block stylesheet_block %}
    <link rel="stylesheet" href="{% static 'css/meal.css' %}">
{% endblock %}

{% block title_block %}
    Meal
{% endblock %}

{% block body_block %}
<h1>{{meal.name}}</h1>
<div id="new_meal_container">
    {% if meal.image %}
        <img id="meal" src="{{meal.image.url}}" alt="Meal Image">
    {% endif %}
    <h3>Instructions</h3>
    {% if meal.instructions %}
        {{meal.instructions}}
    {% else %}
        No instructions
    {% endif %}
    <h3>Ingredients</h3>
    {% if meal.ingredients.all %}
    <ul>
        {% for ingredient in meal.ingredients.all %}
            <li>{{ ingredient.name }} - {{ ingredient.amount|remove_decimal_if_integer }} {{ ingredient.unit }}</li>
        {% endfor %}
    </ul>
    {% else %}
        No ingredients
    {% endif %}
    <br>
    
    <div id="links">
        <button class="button" onclick="window.location.href = '{% url 'MyMealMate:edit_meal' meal.slug %}';">Edit Meal</button>
        <button class="button" onclick="window.location.href = '{% url 'MyMealMate:add_meal_to_shopping_list' meal.slug %}';">Add to Shopping List</button>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <button class="button" type="submit" formaction="{% url 'MyMealMate:delete_meal' meal.slug %}">Delete Recipe</button>
        </form>
        {% if meal.url %}
        <button class="button" onclick="window.location.href = '{{ meal.url }}'">Link to Recipe</button>
        {% endif %}
        <button class="button" onclick="window.location.href = '{% url 'MyMealMate:my_meals' %}';">Back to My Meals</button>
    </div>
</div>
{% endblock %}

templates/MyMealMate/user_hub.html
<!DOCTYPE html>
{% extends 'MyMealMate/base.html' %}
{% load staticfiles %}
{%load MyMealMate_template_tags%}

{% block title_block %}
    User Hub
{% endblock %}

{% block script_block %}
    <script src="{% static 'js/meal_of_the_day.js' %}"></script>
{% endblock %}

{% block stylesheet_block %}
    <link rel="stylesheet" href="{% static 'css/user_hub.css' %}">
{% endblock %}

{% block body_block %}

<div class="title">
    {% if user.first_name %}
        <h1>{{ user.first_name }}'s Hub</h1>
    {% else %}
        <h1>User Hub</h1>
    {% endif %}
</div>

<div class="user_hub">
    <div class="upcoming_meals">
        <h1><a href="{% url 'MyMealMate:schedule' %}">Upcoming Meals</a></h1>
        <div id="meal_schedule">
            {% for meal in upcoming_meals %}
                <div class="meal">
                    <ul>
                        <li><strong>{{ meal.0 }}</strong> - {% for meal_name in meal.1 %}{{ meal_name }}{% if not forloop.last %}, {% endif %}{% endfor %}</li>
                    </ul>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="shopping_list">
        <h1><a href="{% url 'MyMealMate:shopping_list' %}" class="{% if nbar == 'shopping_list' %}active{% endif %}">My Shopping List</a></h1>
        <ul>
            {%if shopping_list_items%}
            {%for shopping_list_item in shopping_list_items%}
                <form action="{%url 'MyMealMate:clicked_from_hub' shopping_list_item.id %}" method="POST">
                    {% csrf_token %}
                    <label><input type="checkbox" value="{{shopping_list_item.id}}" onchange="this.form.submit()"  {%if shopping_list_item.checked%} checked {%endif%} />
                        {% if shopping_list_item.checked %}
                        <s>{{shopping_list_item.name}}{%if shopping_list_item.amount%}: {{shopping_list_item.amount|remove_decimal_if_integer}} {%if shopping_list_item.unit%} {{shopping_list_item.unit}} {%endif%} {%endif%}</s>
                        {%else%}
                        {{shopping_list_item.name}}{%if shopping_list_item.amount%}: {{shopping_list_item.amount|remove_decimal_if_integer}} {%if shopping_list_item.unit%} {{shopping_list_item.unit}} {%endif%} {%endif%}
                        {%endif%}</label> <br/>
                </form>
            {%endfor%}
            {%else%}
                <ul> <li><strong>You currently don't have any items on your list.</strong></li></ul>
            {%endif%}
        </ul>
    </div>
</div>

<div class="meal_of_the_day" meal_of_the_day="{{ meal_of_the_day }}">
    <img class='thumbnail' src="{{ meal_of_the_day.strMealThumb }}"/>
    <div class='meal_content'>
        <h2>Meal of The Day: {{ meal_of_the_day.strMeal }}</h2>
        <div class="flex_meal_content">
            <ul id="ingredients"></ul>
            <form method="POST" action="{% url 'MyMealMate:add_meal_of_the_day' %}" class="add_meal_of_the_day">
                {% csrf_token %}
                <button type="submit" class="button">Add to My Meals</button>  
                <script>displayAddButton('{{ has_meal_of_the_day }}')</script>
            </form>
        </div>
    </div>
</div>

{% endblock %}